spring.application.name=cognito-app

# Environment (set to 'production' when deploying)
app.environment=development

# AWS Cognito Configuration
aws.cognito.userPoolId=eu-central-1_rS9qXL9Ee
aws.cognito.clientId=3t8p938oufoc1pstif4660vhmq
aws.cognito.region=eu-central-1
aws.cognito.domain=https://eu-central-1rs9qxl9ee.auth.eu-central-1.amazoncognito.com
aws.cognito.redirectUri=https://main.d16f2529r3lhi6.amplifyapp.com/
aws.cognito.customLoginUrl=https://main.d2l13mf6ec69fe.amplifyapp.com
aws.cognito.responseType=code
aws.cognito.scope=email openid phone
