spring.application.name=${SPRING_APPLICATION_NAME:cognito-app}

# Server configuration (PORT env var set by Elastic Beanstalk to 5000)
server.port=${PORT:8080}

# Environment (set to 'production' when deploying)
app.environment=${APP_ENVIRONMENT:development}

# AWS Cognito Configuration
aws.cognito.userPoolId=${AWS_COGNITO_USERPOOLID:eu-central-1_rS9qXL9Ee}
aws.cognito.clientId=${AWS_COGNITO_CLIENTID:3t8p938oufoc1pstif4660vhmq}
aws.cognito.region=${AWS_COGNITO_REGION:eu-central-1}
aws.cognito.domain=${AWS_COGNITO_DOMAIN:https://eu-central-1rs9qxl9ee.auth.eu-central-1.amazoncognito.com}
aws.cognito.redirectUri=${AWS_COGNITO_REDIRECTURI:https://main.d16f2529r3lhi6.amplifyapp.com/}
aws.cognito.customLoginUrl=${AWS_COGNITO_CUSTOMLOGINURL:https://main.d2l13mf6ec69fe.amplifyapp.com}
aws.cognito.responseType=${AWS_COGNITO_RESPONSETYPE:code}
aws.cognito.scope=${AWS_COGNITO_SCOPE:email openid phone}
